import { ItemType } from './inventory';

export const orderedTypes = [
  'PORTAL_LINK_KEY',
  'EMITTER_A',
  'EMP_BURSTER',
  'ULTRA_STRIKE',
  'FLIP_CARD',
  'FLIP_CARD:ADA',
  'FLIP_CARD:JARVIS',
  'POWER_CUBE',
  'BOOSTED_POWER_CUBE',
  'BOOSTED_POWER_CUBE_K',
  'RES_SHIELD',
  'EXTRA_SHIELD',
  'TURRET',
  'FORCE_AMP',
  'LINK_AMPLIFIER',
  'ULTRA_LINK_AMP',
  'HEATSINK',
  'MULTIHACK',
  'TRANSMUTER_ATTACK',
  'TRANSMUTER_DEFENSE',
  'MEDIA',
  'CAPSULE',
  'INTEREST_CAPSULE',
  'KEY_CAPSULE',
  'KINETIC_CAPSULE',
  'DRONE',
  'MYSTERIOUS_ITEM_PLACEHOLDER',
  'PLAYER_POWERUP',
  'PLAYER_POWERUP:APEX',
  'PORTAL_POWERUP',
  'PORTAL_POWERUP:FRACK',
  'PORTAL_POWERUP:NEMESIS',
  'PORTAL_POWERUP:TOASTY',
  'PORTAL_POWERUP:EXO5',
  'PORTAL_POWERUP:MAGNUSRE',
  'PORTAL_POWERUP:VIANOIR',
  'PORTAL_POWERUP:VIALUX',
  'PORTAL_POWERUP:INITIO',
  'PORTAL_POWERUP:AEGISNOVA',
  'PORTAL_POWERUP:OBSIDIAN',
  'PORTAL_POWERUP:NIA',
  'PORTAL_POWERUP:ENL',
  'PORTAL_POWERUP:RES',
  'PORTAL_POWERUP:MEET',
  'PORTAL_POWERUP:LOOK',
  'PORTAL_POWERUP:BB_BATTLE',
  'PORTAL_POWERUP:BB_BATTLE_RARE',
  'PORTAL_POWERUP:FW_ENL',
  'PORTAL_POWERUP:FW_RES',
  'PORTAL_POWERUP:BN_BLM',
] as ItemType[];

export function addIfMissing(type: ItemType) {
  if (!orderedTypes.includes(type)) orderedTypes.push(type);
}

export function completeFromTypeList(types: ItemType[]) {
  const known = new Set(orderedTypes);
  for (const type of types) {
    if (!known.has(type)) orderedTypes.push(type);
  }
}
